### ISSUE TITLE
多账号时增加运行完退出游戏和息屏的功能

### ISSUE THREAD

**Issue by cym31153** [tkkcc/ArkLights#146]
多账号运行时运行完不退出游戏导致高耗电

**Comment by tkkcc** [comment]
默认运行完会回到桌面，游戏在后台几乎无耗电

**Comment by cym31153** [comment]
> 默认运行完会回到桌面，游戏在后台几乎无耗电

那有可能是我的问题，会不会有时候不能退回到桌面

**Comment by tkkcc** [comment]
你有没有勾回到桌面呢

**Comment by tkkcc** [comment]
还有一个 关闭游戏，也可以勾

**Comment by tkkcc** [comment]
能复现就拍下来

**Comment by cym31153** [comment]
> 你有没有勾回到桌面呢

我忘记了😂我的问题
您把我的两个issue都关了吧
